# Generated by Django 3.0.2 on 2020-01-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20200109_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='full_name',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.CharField>', max_length=201, unique=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
