# Generated by Django 3.0.2 on 2020-01-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20200116_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='full_name',
            field=models.CharField(default='-', max_length=201, unique=True),
        ),
    ]
