# Generated by Django 3.0.2 on 2020-01-24 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_auto_20200116_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 20, 55, 56, 122195)),
        ),
    ]
