# Generated by Django 3.0.2 on 2020-01-27 23:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_repository_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
