# Generated by Django 3.0.2 on 2020-01-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_auto_20200127_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='description',
            field=models.TextField(default='', null=True),
        ),
    ]
