# Generated by Django 3.0.2 on 2020-01-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_auto_20200128_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='hook_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
